<script setup lang="ts">
import { useRouter } from 'vue-router';

const router = useRouter();

const metrics = [
  {
    title: "叙事弧光 (Narrative Arc)",
    icon: "📈",
    desc: "展示故事的情绪起伏与剧情张力。",
    details: [
      "张力 (Red Line): 代表剧情的悬疑、冲突或紧迫感。",
      "情感 (Cyan Line): 代表当前段落的正面/负面情绪指数。",
      "理想状态：两条线应随剧情发展而波动，高潮处通常伴随高张力。"
    ]
  },
  {
    title: "关系动力学 (Relationship Dynamics)",
    icon: "🕸️",
    desc: "自动分析角色与故事段落之间的情感互动。",
    details: [
      "绿色连线: 代表积极、友好或建设性的互动。",
      "红色连线: 代表冲突、敌对或紧张的互动。",
      "节点大小: 代表该章节或角色的戏份比重。"
    ]
  },
  {
    title: "文笔雷达 (Style Radar)",
    icon: "📡",
    desc: "监控写作风格的生动程度与感官描写。",
    details: [
      "画面感 (Show Ratio): 动词+名词 vs 形容词+副词的比例。越高代表越倾向于'展示'而非'讲述'。",
      "感官密度 (Sensory): 色、香、味、触、声等感官词汇的密度。",
      "形容词警告: 当段落中形容词占比过高时触发，提示可能存在'堆砌辞藻'的问题。"
    ]
  },
  {
    title: "语义漂移 (Semantic Drift)",
    icon: "🧭",
    desc: "测量当前故事走向与初始设定或第一章的偏差。",
    details: [
      "0% - 20%: 紧扣主题。",
      "20% - 60%: 正常发展，情节展开。",
      "> 60%: 可能发生神转折或跑题。"
    ]
  },
  {
    title: "对话含量 (Dialogue Ratio)",
    icon: "💬",
    desc: "统计文中对话（引号内内容）与叙述性文字的比例。",
    details: [
      "根据小说类型不同，理想比例不同。",
      "一般来说，30%-50% 的对话比例能保持较好的阅读节奏。"
    ]
  }
];
</script>

<template>
  <div class="min-h-screen font-sans text-slate-200 relative overflow-hidden flex flex-col items-center">
    
    <!-- Deep Space Background -->
    <div class="fixed inset-0 pointer-events-none z-0">
        <div class="absolute inset-0 bg-gradient-to-b from-[#0f0c29] via-[#302b63] to-[#24243e]"></div>
        <div class="stars absolute inset-0 opacity-50"></div> 
    </div>

    <div class="relative z-10 w-full max-w-4xl px-4 py-8">
      <header class="mb-8 flex items-center justify-between">
        <h1 class="text-3xl font-serif font-bold text-amber-300 tracking-wider flex items-center gap-2">
            <span class="text-4xl">📖</span> 全知仪表盘 · 指标指南
        </h1>
        <button 
          @click="router.back()" 
          class="px-4 py-2 glass-btn rounded-full text-sm text-cyan-300 hover:bg-cyan-500/10 hover:shadow-[0_0_15px_rgba(34,211,238,0.4)] transition-all"
        >
          ← 返回工作台 (Back)
        </button>
      </header>

      <div class="grid gap-6">
        <div 
          v-for="m in metrics" 
          :key="m.title" 
          class="glass-panel p-6 rounded-2xl hover:bg-white/5 transition duration-300"
        >
          <div class="flex items-start gap-4">
            <div class="text-4xl bg-white/5 p-3 rounded-xl border border-white/10">{{ m.icon }}</div>
            <div>
              <h2 class="text-xl font-bold text-slate-200 mb-2">{{ m.title }}</h2>
              <p class="text-slate-400 mb-4">{{ m.desc }}</p>
              
              <ul class="space-y-2">
                <li v-for="(detail, i) in m.details" :key="i" class="flex gap-2 text-sm text-slate-400">
                  <span class="text-cyan-400 mt-1">❖</span>
                  <span>{{ detail }}</span>
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
      
      <footer class="mt-12 text-center text-slate-500 text-xs uppercase tracking-widest">
        Generated by Multiverse Engine v1.0
      </footer>
    </div>
  </div>
</template>

<style scoped>
.glass-panel {
    background: rgba(255, 255, 255, 0.03);
    backdrop-filter: blur(16px);
    border: 1px solid rgba(255, 255, 255, 0.05);
    box-shadow: 0 4px 30px rgba(0, 0, 0, 0.1);
}
.glass-btn {
    background: rgba(255, 255, 255, 0.05);
    border: 1px solid rgba(255, 255, 255, 0.1);
    transition: all 0.3s ease;
}

/* Star Background (Helper) */
.stars {
    background-image: 
        radial-gradient(white, rgba(255,255,255,.2) 2px, transparent 3px),
        radial-gradient(white, rgba(255,255,255,.15) 1px, transparent 2px),
        radial-gradient(white, rgba(255,255,255,.1) 2px, transparent 3px);
    background-size: 550px 550px, 350px 350px, 250px 250px;
    background-position: 0 0, 40px 60px, 130px 270px;
}
</style>
